export const LIST_LOAD = ' LIST_LOAD'

export const SET_FILTER_VALUE = 'SET_FILTER_VALUE'
export const SET_FILTER_GENDER = 'SET_FILTER_GENDER'
export const SET_FILTER_TYPE = 'SET_FILTER_TYPE'
export const SET_FILTER_PRICE = 'SET_FILTER_PRICE'
export const CLEAR_FILTRES = 'CLEAR_FILTRES'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
